name: Upload PYPI Package

on:
  release:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    environment:
      name: pypi
      url: https://pypi.org/p/pydantic-duality

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-python-poetry
      - name: Publish
        run: poetry build && poetry publish
