name: Tests
on:
  push:
    branches: [main]
    paths:
      - "**.py"
      - "**.toml"
      - "**.lock"
  pull_request:
    branches: [main]
    types: [opened, synchronize]
    paths:
      - "**.py"
      - "**.toml"
      - "**.lock"
      - "**.yaml"

jobs:
  Tests:
    strategy:
      fail-fast: true
      matrix:
        include:
          - os: ubuntu-latest
            python-version: "3.9"
          - os: ubuntu-latest
            python-version: "3.10"
          - os: ubuntu-latest
            python-version: "3.11"
          - os: ubuntu-latest
            python-version: "3.12"
          - os: ubuntu-latest
            python-version: "3.13"
          - os: windows-latest
            python-version: "3.11"
          - os: macos-latest
            python-version: "3.11"
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-python-poetry
        with:
          python-version: ${{ matrix.python-version }}
      - run: poetry run coverage run --source=. --parallel-mode -m pytest tests
      - name: Upload coverage results
        uses: actions/upload-artifact@v3
        if: matrix.os == 'ubuntu-latest' # Cross-platform coverage combination doesn't work
        with:
          name: main-tests-coverage-results
          path: coverage/
  Coverage:
    needs: [Tests]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download main tests coverage info
        uses: actions/download-artifact@v3
        with:
          name: main-tests-coverage-results
          path: coverage/
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - run: pip install 'coverage[toml]'
      - run: coverage combine
      - run: coverage xml
      - name: Upload to Codecov
        uses: codecov/codecov-action@v4
        env:
          fail_ci_if_error: true
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      - run: coverage report --fail-under=100
