name: Tests
on:
  push:
    branches: [main]
    paths:
      - "**.py"
      - "**.toml"
      - "**.lock"
  pull_request:
    branches: [main]
    types: [opened, synchronize]
    paths:
      - "**.py"
      - "**.toml"
      - "**.lock"

jobs:
  Tests:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/setup-python-poetry
        with:
          python-version: ${{ matrix.python-version }}
      - name: Test
        run: poetry run coverage run --parallel-mode -m pytest .
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: coverage-directory
          path: ./coverage
  
  Upload-Coverage:
    runs-on: ubuntu-latest
    needs: [ Tests ]
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/setup-python-poetry
      - uses: actions/download-artifact@v2
      - run: poetry run coverage combine
      - name: Upload to Codecov
        uses: codecov/codecov-action@v2
